/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fi_tkk_ics_jbliss_Digraph */

#ifndef _Included_fi_tkk_ics_jbliss_Digraph
#define _Included_fi_tkk_ics_jbliss_Digraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_fi_tkk_ics_jbliss_Digraph_create
  (JNIEnv *, jobject);

/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fi_tkk_ics_jbliss_Digraph_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    _add_vertex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_fi_tkk_ics_jbliss_Digraph__1add_1vertex
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    _add_edge
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_fi_tkk_ics_jbliss_Digraph__1add_1edge
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    _find_automorphisms
 * Signature: (JLfi/tkk/ics/jbliss/Reporter;)V
 */
JNIEXPORT void JNICALL Java_fi_tkk_ics_jbliss_Digraph__1find_1automorphisms
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     fi_tkk_ics_jbliss_Digraph
 * Method:    _canonical_labeling
 * Signature: (JLfi/tkk/ics/jbliss/Reporter;)[I
 */
JNIEXPORT jintArray JNICALL Java_fi_tkk_ics_jbliss_Digraph__1canonical_1labeling
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
